### PR TITLE
zephyr: Set IS_MCUBOOT for Zephyr builds

### PR DESCRIPTION
**Pull request by carlescufi**
Enable the new IS_MCUBOOT Kconfig option on Zephyr builds and move the Kconfig file to boot/zephyr

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
LGTM

**Comment by utzig** [comment]
Yup, looks good to me, but I will add some zephyr reviewers to confirm!

**Comment by carlescufi** [comment]
Would it be better instead to do `select IS_MCUBOOT`
in the root `Kconfig` ?

**Comment by nvlsianpu** [comment]
I think yes - Advantage would be that it will be forced to be selected.

**Comment by carlescufi** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/5789

**Comment by carlescufi** [comment]
@utzig @nvlsianpu I've replaced it with a "mandatory" `MCUBOOT` option

**Comment by carlescufi** [comment]
I'm going to close this because it adds a circular dependency between Zephyr and MCUboot, and I would like to avoid that

**Pull request closed without merging**
