### PR TITLE
Add overwrite-only upgrade

### PR DESCRIPTION
**Pull request by d3zd3z**
Implement an overwrite-only upgrade as well as a query to determine at run time if that is available.

### CODE REVIEW

**Comment by utzig** [comment]
Temporarily I think this is ok. But would be interesting to support both upgrade methods in the bootloader and define a semantics for the images to chose which method they prefer. What do you think?

**Comment by d3zd3z** [comment]
> Temporarily I think this is ok. But would be interesting to support both upgrade methods in the bootloader and define a semantics for the images to chose which method they prefer. What do you think?

It would also help testing to be able to have both methods compiled in. However, the main motivation behind writing this code is to make the bootloader code more simple. People are a bit leery of complexity in the bootloader itself.

**Comment by d3zd3z** [comment]
And, there actually are already semantics for the image to choose. If the image trailer has image_ok, the image will be marked as ok after the copy, and the bootloader will not try to revert. Perhaps in normal compilation, that should use this code instead of trying to swap. If anything, the upgrade should be faster that way.

**Comment by d3zd3z** [comment]
Rebased to resolve merge conflicts.

**Pull request merged**
