### PR TITLE
Boot serial mynewt

### PR DESCRIPTION
**Pull request by utzig**
This enables boot serial functionality on Mynewt.

DO NOT MERGE - under test; needs to be rebased when #152 is merged.

### CODE REVIEW

**Comment by d3zd3z** [comment]
Now that #152 has been merged, does this need to rebased, or just the description changed and it submitted?

**Comment by utzig** [comment]
I rebased on master locally but it doesn't build anymore. I will fix soon, when I finish some other stuff.

**Comment by utzig** [comment]
@d3zd3z Please approve/merge!

**Comment by andrzej-kaczmarek** [comment]
works for me

```
andk@t450s ~/devel/mynewt$ newtmgr --conn ttyacm0 image list
Images:
Split status: N/A
andk@t450s ~/devel/mynewt$ newt create-image -2 blinky 1.0.0.0
App image succesfully generated: /home/andk/devel/mynewt/bin/targets/blinky/app/apps/blinky/blinky.img
andk@t450s ~/devel/mynewt$ newtmgr --conn ttyacm0 image upload /home/andk/devel/mynewt/bin/targets/blinky/app/apps/blinky/blinky.img
56
120
<snip>
Done
andk@t450s ~/devel/mynewt$ newtmgr --conn ttyacm0 image list
Images:
 slot=0
    version: 1.0.0.0
    bootable: false
    flags: 
    hash: Unavailable
Split status: N/A
```

**Pull request merged**
